apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: deno
spec:
  resources:
    - name: git-source
      type: git
  tasks:
  - name: test
    taskRef:
      name: test-deno
    resources:
      inputs:
        - name: git-source
          resource: git-source
