apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: sample
  namespace: default
spec:
  type: git
  params:
    - name: url
      value: https://github.com/iupay/sample.git
    - name: revision
      value: master
